# Generated by Django 4.1.3 on 2023-03-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorId', models.PositiveIntegerField(blank=True, null=True)),
                ('patientName', models.CharField(blank=True, max_length=50, null=True)),
                ('patientTitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='คำนำหน้าชื่อ')),
                ('doctorName', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อการนัด')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='คำอธิบายเพิ่มเติม')),
                ('date', models.DateField(verbose_name='วันที่นัดคนไข้')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.treatmenthistory')),
            ],
        ),
    ]
