# Generated by Django 4.1.3 on 2023-03-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineFrontStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medCode', models.CharField(max_length=50, unique=True, verbose_name='รหัสยา')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อยา')),
                ('slug', models.SlugField(max_length=200)),
                ('tradeName', models.CharField(max_length=100, verbose_name='ชื่อทางการค้า')),
                ('genericName', models.CharField(max_length=100, verbose_name='ชื่อสามัญทางยา')),
                ('initial', models.CharField(max_length=20, verbose_name='ชื่อย่อ')),
                ('countingUnit', models.FloatField(max_length=10, verbose_name='หน่วยนับ')),
                ('costPrice', models.FloatField(verbose_name='ราคาซื้อ')),
                ('sellingPrice', models.FloatField(verbose_name='ราคาขาย')),
                ('medicineStrength', models.CharField(max_length=500, verbose_name='ความแรงของยา')),
                ('indication', models.CharField(max_length=500, verbose_name='สรรพคุณของยา')),
                ('direction', models.CharField(max_length=500, verbose_name='คำเตือนการใช้ยา')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now=True)),
                ('nlem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Unit.thailandnationallistofessentialmedicines', verbose_name='บัญชียาหลักแห่งชาติ')),
                ('packingUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Unit.medicineunit', verbose_name='หน่วยบรรจุ')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Unit.medicinetype', verbose_name='ประเภทของยา')),
            ],
        ),
    ]
