# Generated by Django 4.1.3 on 2023-03-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unit', '0001_initial'),
        ('MedicineStock', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อคนไข้')),
                ('doctorName', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อหมอ')),
                ('medicineAmount', models.IntegerField(verbose_name='จำนวน')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MedicineStock.medicine', verbose_name='ชื่อยา')),
                ('medicineUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Unit.medicineunit', verbose_name='หน่วยบรรจุ')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.treatmenthistory')),
            ],
        ),
    ]
