# Generated by Django 4.1.3 on 2023-03-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='น้ำหนัก')),
                ('height', models.FloatField(blank=True, max_length=10, null=True, verbose_name='ส่วนสูง')),
                ('temp', models.FloatField(blank=True, max_length=10, null=True, verbose_name='อุณหภูมิ')),
                ('pressure', models.CharField(blank=True, max_length=10, null=True, verbose_name='ความดันโลหิต')),
                ('pulse', models.CharField(blank=True, max_length=10, null=True, verbose_name='ชีพจร')),
                ('initialSymptoms', models.CharField(blank=True, max_length=1000, null=True, verbose_name='อาการ')),
                ('nurseId', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn', models.CharField(max_length=50, unique=True, verbose_name='เลขประจำตัวคนไข้')),
                ('name', models.CharField(max_length=50, verbose_name='ชื่อ-นามสกุล')),
                ('slug', models.SlugField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('ไม่ระบุ', 'ไม่ระบุ')], default='ชาย', max_length=10, verbose_name='เพศ')),
                ('dob', models.CharField(max_length=10, verbose_name='วันเกิด')),
                ('phone', models.CharField(max_length=10, verbose_name='เบอร์โทรศัพท์')),
                ('idCard', models.CharField(max_length=13, unique=True, verbose_name='เลขบัตรประจำตัวประชาชน')),
                ('address', models.TextField(max_length=500, verbose_name='ที่อยู่')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ที่อยู่อีเมล์')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='Image', verbose_name='รูปภาพ')),
                ('bloodType', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10, verbose_name='หมู่เลือด')),
                ('underlyingDisease', models.CharField(blank=True, max_length=500, null=True, verbose_name='โรคประจำตัว')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unit.nametitle', verbose_name='คำนำหน้าชื่อ')),
            ],
        ),
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientTitle', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientTitle', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=50)),
                ('doctorName', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อหมอ')),
                ('initialSymptoms', models.CharField(blank=True, max_length=1000, null=True, verbose_name='อาการ')),
                ('initialSymptoms1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ผลการวินิจฉัย')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('app', models.CharField(blank=True, max_length=50, null=True)),
                ('pres', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('initial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.initialsymptoms')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessfulTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(blank=True, max_length=50, null=True)),
                ('treatmentName', models.CharField(blank=True, max_length=500, null=True)),
                ('queueStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment', models.CharField(blank=True, max_length=50, null=True)),
                ('prescription', models.CharField(blank=True, max_length=50, null=True)),
                ('status1', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patientqueue')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.treatmenthistory')),
            ],
        ),
        migrations.AddField(
            model_name='initialsymptoms',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorId', models.PositiveIntegerField(blank=True, null=True)),
                ('patientName', models.CharField(blank=True, max_length=40, null=True)),
                ('patientTitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='คำนำหน้าชื่อ')),
                ('doctorName', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อการนัด')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='คำอธิบายเพิ่มเติม')),
                ('date', models.DateField(max_length=100, verbose_name='วันที่นัดคนไข้')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขประจำตัวคนไข้')),
                ('patientTitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='คำนำหน้าชื่อ')),
                ('patientName', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อคนไข้')),
                ('doctorName', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อหมอ')),
                ('sequence', models.IntegerField(blank=True, null=True, verbose_name='ลำดับการแพ้ยา')),
                ('allergicMedicineName', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อยาที่แพ้')),
                ('allergicSymptom', models.CharField(blank=True, max_length=500, verbose_name='อาการแพ้ยา')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
